name: first Workflow

# To get trigger on every push in this repo in any branch
on: push

jobs:
 job1 : 
   name : job1
   runs-on : ubuntu-latest
   steps: 
      name: Running single command in job1
      run: echo "Hi this is my 1st GitHub workflow"
      
      name: Running another command
      run: echo "Hi This is 2nd command"
