name: first Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest

    steps:
      - name: Print Node version
        run: node --version

      - name: Print npm version
        run: npm --version

      - name: Print message
        run: echo "My first GitHub Actions CI pipeline"
